---
#---------------------------
#---------------------------
# 首页
# Index Page
index:
  banner_img: /images/index-page-banner.jpg # 首页 Banner 头图，以下相同
  banner_img_height: 100 # 头图高度，屏幕百分比，available: 0 - 100
  banner_mask_alpha: 0.3 # 头图黑色蒙版的透明度，available: 0 - 1.0， 0 是完全透明（无蒙版），1 是完全不透明
  post_default_img: "" # 默认的文章封面图，当没有指定 index_img 时会使用该图片，若都为空则不显示任何图片
  slogan: # 首页副标题的独立设置
    enable: true # 为 false 则不显示任何内容
    text: "Think different." # 为空则按 hexo config.subtitle 显示
  auto_excerpt:
    enable: true
  post_url_target: _self # available: _blank | _self
  post_meta: # 是否显示文章信息（时间、分类、标签）
    date: true
    category: true
    tag: true

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /images/archive-page-banner.jpg

#---------------------------
# 分类归档页
# Categories Page
#---------------------------
category:
  banner_img: /images/category-page-banner.jpg

#---------------------------
# 标签归档页
# Tags Page
#---------------------------
tag:
  banner_img: /images/tag-page-banner.jpg

#---------------------------
# 页头
# Header
#---------------------------
navbar:
  blog_title: 鲱鱼罐头大吃两碗 # 导航栏左侧的标题，为空则按 hexo config.title 显示
  ground_glass: # 导航栏毛玻璃特效，实验性功能，可能会造成页面滚动掉帧和抖动，部分浏览器不支持会自动不生效
    enable: false
    px: 3 # 模糊像素，只能为数字，数字越大模糊度越高
    alpha: 0.7 # 透明度，只能为数字，范围0~1，数字越大透明度越低，注意透明过度可能看不清菜单字体
  menu: # 可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - {
        key: "category",
        link: "/categories/",
        icon: "iconfont icon-category-fill",
      }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    #- { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    #- { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }  # 友链页，把前面#去掉即可展示

#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  statistics: # 展示网站的 PV、UV 统计数
    enable: true
    source: "busuanzi" # 统计数据来源，可选：busuanzi | leancloud，使用 leancloud 需要在 web_analytics 中设置 api 参数，使用 busuanzi 注意可能间歇抽风
    pv_format: "总访问量 {} 次" # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

  beian: # The footer of China's website policy, other areas keep disable
    enable: false
    icp_text: 京ICP证123456号 # ICP证号
    police_text: 京公网安备12345678号 # 公安备案号，不填则只显示ICP
    police_code: 12345678 # 公安备案的编号，用于URL跳转查询
    police_icon: /img/police_beian.png # 公安备案的图片. 为空时不显示备案图片

scroll_top_arrow: # 向顶部滚动的箭头
  enable: true
